// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripLog.Models;

namespace TripLog.Migrations
{
    [DbContext(typeof(TripContext))]
    partial class TripContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("TripLog.Models.Trip", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccommodationEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccommodationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccommodationPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThingToDo1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThingToDo2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThingToDo3")
                        .HasColumnType("TEXT");

                    b.HasKey("TripID");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripID = 1,
                            AccommodationEmail = "info@nyhabitat.com",
                            AccommodationName = "NY Habitat",
                            AccommodationPhone = "212.255.8018",
                            Destination = "New York City",
                            EndDate = new DateTime(2010, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2009, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThingToDo1 = "Visit Times Square",
                            ThingToDo2 = "See 30 Rockefeller Plaza",
                            ThingToDo3 = "Check out Union Square farmer's market"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
